image: docker.io/maven:3.6.1-amazoncorretto-8

stages:
  - build
  - unit_test
  - build_app_image
  - deploy_to_env
  - e2e_test
  - publish
  - development
  - staging
  - prod

  
variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build_code:
  stage: build
  script:
    - mvn compile

unit_test:
  stage: unit_test
  script:
    - mvn compile

build_app_image:
  stage: build_app_image
  script:
    - echo "Build Docker image for this app version"

deploy_to_shared_env:
  stage: deploy_to_env
  script:
    - echo "Deploy this version of image in an environment"

Run_e2e_test:
  stage: e2e_test
  script:
    - echo "Automated test to validate the app"

publish:
  stage: publish
  script:
    - echo "Publish this image to image registry for rollout"

deploy_to_dev:
  stage: development
  script:
    - echo "Deploy to a newly provisioned stack"

deploy_to_stage:
  stage: staging
  script:
    - echo "Deploy to stage"

deploy_to_prod:
 stage: prod
 script:
   - echo "Deploy to prod"